import type { Lesson, LessonType } from "../types.js";
import { lessonTypeLabel } from "../lessonTemplates.js";
import { LessonRenderer } from "./LessonRenderer.js";

// Each of these reads as a self-contained visual (its own counter/title/
// stations sit inside the component itself) - the type label on top of
// them is redundant chrome that breaks that illusion, unlike a plain text
// or quiz block where the label is the only cue to what kind of lesson it is.
const DYNAMIC_COMPONENT_TYPES: Set<LessonType> = new Set([
  "dial",
  "pipeline",
  "presentationDial",
  "cardGrid",
  "hotspots",
]);

export function StudentLessonBlock({
  lesson,
  isComplete,
  onComplete,
}: {
  lesson: Lesson;
  isComplete: boolean;
  onComplete: () => void;
}) {
  const isDynamicComponent = DYNAMIC_COMPONENT_TYPES.has(lesson.type);
  return (
    <div
      className={`student-lesson${isComplete ? " is-complete" : ""}${isDynamicComponent ? " is-floating" : ""}`}
    >
      <div className="student-lesson-header">
        <div className="student-lesson-badges">
          {!isDynamicComponent && <span className="student-lesson-type">{lessonTypeLabel(lesson.type)}</span>}
          {lesson.source === "ai_generated" && (
            <span className="student-lesson-ai-badge" title="This lesson's content was generated by AI">
              AI-generated
            </span>
          )}
        </div>
        {isComplete && <span className="student-lesson-complete-badge">✓ Completed</span>}
      </div>
      <LessonRenderer lesson={lesson} isComplete={isComplete} onComplete={onComplete} />
    </div>
  );
}
