import type { Lesson } from "../types.js";
import { lessonTypeLabel } from "../lessonTemplates.js";
import { LessonRenderer } from "./LessonRenderer.js";

export function StudentLessonBlock({
  lesson,
  isComplete,
  onComplete,
}: {
  lesson: Lesson;
  isComplete: boolean;
  onComplete: () => void;
}) {
  return (
    <div className={`student-lesson${isComplete ? " is-complete" : ""}`}>
      <div className="student-lesson-header">
        <div className="student-lesson-badges">
          <span className="student-lesson-type">{lessonTypeLabel(lesson.type)}</span>
          {lesson.source === "ai_generated" && (
            <span className="student-lesson-ai-badge" title="This lesson's content was generated by AI">
              AI-generated
            </span>
          )}
        </div>
        {isComplete && <span className="student-lesson-complete-badge">✓ Completed</span>}
      </div>
      <LessonRenderer lesson={lesson} isComplete={isComplete} onComplete={onComplete} />
    </div>
  );
}
